# Generated by Django 4.1.3 on 2022-11-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id_user',
            new_name='user',
        ),
    ]
