# Generated by Django 4.1.3 on 2022-12-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_id_user_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_path',
            field=models.ImageField(upload_to='D:\\Kuliah Alfons\\Python Projects\travelMates\\images'),
        ),
    ]
