# Generated by Django 4.1.3 on 2022-12-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_post_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
